# Generated by Django 6.0.2 on 2026-02-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='stock',
        ),
    ]
