# Generated by Django 5.2.11 on 2026-02-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0002_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=20),
        ),
    ]
