# Generated by Django 5.2.11 on 2026-02-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
