# Generated by Django 6.0.2 on 2026-03-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_conversation_pair',
        ),
    ]
